version: '3.8'
services:
  server:
    image: 'nginx:mainline-alpine3.18-perl'
    restart: no
    volumes:
      - ./dist/ngx-form-control-errors/browser:/usr/share/nginx/html
      - ./tmp/nginx.conf:/etc/nginx/conf.d
    ports:
      - 3000:80
